name: Render CI/CD Pipeline

on:
  push:
    branches:
      - main  # Jo tamaru branch name 'master' hoy to ahiya 'master' lakho

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Render Deploy Hook
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}